apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
  template:
    metadata:
      labels:
        app: serviceb
    spec:
      containers:
        - name: serviceb
          image: blitzlicht123/serviceb
          ports:
            - containerPort: 8080